name: Interiors
favicon: null
layout_spectrum: 0.5632754908874631
typography_spectrum: 0.6914374786429107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7811009529978037
  lightness: 0.1858046285342425
  saturation: 0.17702472885139287
  rhythmicContrast: 0.6873251632787287
purpose: []
